-- MySQL Script generated by MySQL Workbench
-- Wed Aug 25 18:29:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cocdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cocdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cocdb` DEFAULT CHARACTER SET utf8mb4 ;
USE `cocdb` ;

-- -----------------------------------------------------
-- Table `cocdb`.`prefectures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`prefectures` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`prefectures` (
  `prefecture_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `is_default` TINYINT(1) NOT NULL COMMENT '0: Not default, 1: Default',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`prefecture_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`users` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`users` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(2) NOT NULL COMMENT '1: General user, 2: Host user',
  `login_type` VARCHAR(45) NOT NULL COMMENT '‘EMAIL’, ‘INSTAGRAM’, ‘FACEBOOK’, ‘TWITTER’',
  `email` VARCHAR(254) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Password encrypted.',
  `remember_token` VARCHAR(255) NULL DEFAULT NULL,
  `last_name_kanji` VARCHAR(255) NOT NULL COMMENT 'Specified for a host user.',
  `first_name_kanji` VARCHAR(255) NOT NULL COMMENT 'Specified for a host user.',
  `last_name_kana` VARCHAR(255) NOT NULL COMMENT 'Specified for a host user.',
  `first_name_kana` VARCHAR(255) NOT NULL COMMENT 'Specified for a host user.',
  `nickname` VARCHAR(255) NOT NULL,
  `sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not known, 1: Male, 2: Female, 9: Not applicable',
  `date_of_birth` DATE NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Ex.) “090-2233-4455”',
  `zip_code` CHAR(8) NULL DEFAULT NULL,
  `prefecture_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `subsequent_address` VARCHAR(255) NULL DEFAULT NULL,
  `bank_name` VARCHAR(255) NULL DEFAULT NULL,
  `branch_name` VARCHAR(255) NULL DEFAULT NULL,
  `account_type` TINYINT(2) NULL DEFAULT NULL COMMENT '1: Savings account, 2: Postal savings',
  `account_number` VARCHAR(7) NULL DEFAULT NULL,
  `account_last_name` VARCHAR(255) NULL DEFAULT NULL,
  `account_first_name` VARCHAR(255) NULL DEFAULT NULL,
  `interests` VARCHAR(1000) NULL DEFAULT NULL,
  `points_balance` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'When a user_points record is created, the same value as user_points.points_balance is stored.',
  `points_received` DECIMAL(15,0) NOT NULL DEFAULT 0 COMMENT 'Points received as tipping.',
  `is_authenticated` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not authenticated, 1: Authenticated, 2: No authentication required',
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not archived, 1: Archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_prefectures1_idx` (`prefecture_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_prefectures1`
    FOREIGN KEY (`prefecture_id`)
    REFERENCES `cocdb`.`prefectures` (`prefecture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`events` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`events` (
  `event_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `body` TEXT NOT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not archived, 1: Archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`image_paths`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`image_paths` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`image_paths` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `event_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `file_name` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”000000000061568564639.png\"',
  `dir_path` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”users/6/profiles/\"',
  `image_url` VARCHAR(255) NOT NULL COMMENT 'Ex.) \"https://s3-appname-jp.s3.ap-northeast-1.amazonaws.com/users/6/profiles/000000000061568564639.png\"',
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_paths_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_image_paths_events1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_image_paths_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_paths_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `cocdb`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`points_packages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`points_packages` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`points_packages` (
  `points_package_id` INT(11) UNSIGNED NOT NULL,
  `apple_product_id` VARCHAR(255) NULL DEFAULT NULL,
  `google_product_id` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL(15,0) NOT NULL,
  `points` DECIMAL(15,0) NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`points_package_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`user_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`user_points` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`user_points` (
  `user_point_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `type` TINYINT(2) NOT NULL COMMENT '1: Deposit, 2: Withdrawal',
  `deposit_points` DECIMAL(15,0) NULL DEFAULT NULL,
  `deposit_reason` TINYINT(2) NULL DEFAULT NULL COMMENT '1: Purchase',
  `withdrawal_points` DECIMAL(15,0) NULL DEFAULT NULL,
  `withdrawal_reason` TINYINT(2) NULL DEFAULT NULL COMMENT '1: Event entry, 2: Exchange for a gift',
  `points_balance` DECIMAL(15,0) NOT NULL,
  `transacted_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_point_id`),
  INDEX `fk_user_points_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_points_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`points_package_purchase_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`points_package_purchase_histories` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`points_package_purchase_histories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_point_id` INT(11) UNSIGNED NOT NULL,
  `points_package_id` INT(11) UNSIGNED NOT NULL,
  `payment_amount` DECIMAL(15,0) NOT NULL,
  `purchased_at` DATETIME NOT NULL,
  `apple_trans_id` VARCHAR(255) NULL DEFAULT NULL,
  `google_trans_id` VARCHAR(255) NULL DEFAULT NULL,
  `apple_receipt` TEXT NULL DEFAULT NULL,
  `google_receipt` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_points_package_purchase_histories_user_points1_idx` (`user_point_id` ASC) VISIBLE,
  INDEX `fk_points_package_purchase_histories_points_packages1_idx` (`points_package_id` ASC) VISIBLE,
  CONSTRAINT `fk_points_package_purchase_histories_user_points1`
    FOREIGN KEY (`user_point_id`)
    REFERENCES `cocdb`.`user_points` (`user_point_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_points_package_purchase_histories_points_packages1`
    FOREIGN KEY (`points_package_id`)
    REFERENCES `cocdb`.`points_packages` (`points_package_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`gifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`gifts` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`gifts` (
  `gift_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `points_spent` DECIMAL(15,0) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`gift_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`user_gifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`user_gifts` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`user_gifts` (
  `user_gift_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `gift_id` INT(11) UNSIGNED NOT NULL,
  `status` TINYINT(2) NOT NULL COMMENT '0: Unused, 1: Used',
  `used_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`user_gift_id`),
  INDEX `fk_user_gifts_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_gifts_gifts1_idx` (`gift_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_gifts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_gifts_gifts1`
    FOREIGN KEY (`gift_id`)
    REFERENCES `cocdb`.`gifts` (`gift_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`gift_purchase_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`gift_purchase_histories` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`gift_purchase_histories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_gift_id` INT(11) UNSIGNED NOT NULL,
  `user_point_id` INT(11) UNSIGNED NOT NULL,
  `points_spent` DECIMAL(15,0) NOT NULL,
  `purchased_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gift_purchase_histories_user_gifts1_idx` (`user_gift_id` ASC) VISIBLE,
  INDEX `fk_gift_purchase_histories_user_points1_idx` (`user_point_id` ASC) VISIBLE,
  CONSTRAINT `fk_gift_purchase_histories_user_gifts1`
    FOREIGN KEY (`user_gift_id`)
    REFERENCES `cocdb`.`user_gifts` (`user_gift_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_purchase_histories_user_points1`
    FOREIGN KEY (`user_point_id`)
    REFERENCES `cocdb`.`user_points` (`user_point_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`gift_tipping_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`gift_tipping_histories` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`gift_tipping_histories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_gift_id` INT(11) UNSIGNED NOT NULL,
  `to_user_id` INT(11) UNSIGNED NOT NULL,
  `points_equivalent` DECIMAL(15,0) NOT NULL,
  `tipped_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gift_tipping_histories_user_gifts1_idx` (`user_gift_id` ASC) VISIBLE,
  INDEX `fk_gift_tipping_histories_users1_idx` (`to_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_gift_tipping_histories_user_gifts1`
    FOREIGN KEY (`user_gift_id`)
    REFERENCES `cocdb`.`user_gifts` (`user_gift_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gift_tipping_histories_users1`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`mgmt_portal_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`mgmt_portal_users` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`mgmt_portal_users` (
  `mgmt_portal_user_id` INT(11) UNSIGNED NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` VARCHAR(255) NOT NULL COMMENT 'Password encrypted.',
  `remember_token` VARCHAR(255) NULL DEFAULT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not archived, 1: Archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`mgmt_portal_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`email_authns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`email_authns` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`email_authns` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(2) NOT NULL COMMENT '1: General user, 2: Mgmt portal user',
  `email` VARCHAR(254) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`password_resets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`password_resets` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`password_resets` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type` TINYINT(2) NOT NULL COMMENT '1: General user, 2: Mgmt portal user',
  `email` VARCHAR(254) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`refresh_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`refresh_tokens` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`refresh_tokens` (
  `refresh_token_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `encrypted_refresh_token` VARCHAR(255) NOT NULL COMMENT 'The value of a refresh token encrypted with SHA256.',
  `expires_in` DATETIME NOT NULL,
  `is_blacklisted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not blacklisted, 1: Blacklisted',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`refresh_token_id`),
  INDEX `fk_refresh_tokens_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_refresh_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`device_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`device_tokens` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`device_tokens` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `platform` TINYINT(1) NOT NULL COMMENT '1: iOS, 2: Android',
  `token` VARCHAR(255) NOT NULL,
  `invalidated_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_device_tokens_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_device_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`related_links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`related_links` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`related_links` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `link_url` VARCHAR(255) NOT NULL,
  `file_name` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”1568564639.png\"',
  `dir_path` VARCHAR(255) NOT NULL COMMENT 'Ex.) ”related-links/6/\"',
  `image_url` VARCHAR(255) NOT NULL COMMENT 'Ex.) \"https://s3-appname-jp.s3.ap-northeast-1.amazonaws.com/related-links/6/1568564639.png\"',
  `display_order` TINYINT(2) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`leagues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`leagues` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`leagues` (
  `league_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` INT(11) UNSIGNED NOT NULL,
  `type` TINYINT(2) NOT NULL COMMENT '1: Preliminary round, 2: Final round',
  `parent_league_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `entry_start_datetime` DATETIME NULL DEFAULT NULL,
  `entry_end_datetime` DATETIME NULL DEFAULT NULL,
  `entry_fee` DECIMAL(15,0) NOT NULL,
  `fixed_num` INT(11) NULL DEFAULT NULL,
  `num_of_applicants` INT(11) NULL DEFAULT NULL,
  `start_datetime` DATETIME NOT NULL,
  `end_datetime` DATETIME NOT NULL,
  `is_archived` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not archived, 1: Archived',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`league_id`),
  INDEX `fk_leagues_events1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_leagues_leagues1_idx` (`parent_league_id` ASC) VISIBLE,
  CONSTRAINT `fk_leagues_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `cocdb`.`events` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leagues_leagues1`
    FOREIGN KEY (`parent_league_id`)
    REFERENCES `cocdb`.`leagues` (`league_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`applicants` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`applicants` (
  `applicant_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `league_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`applicant_id`),
  INDEX `fk_applicants_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_applicants_leagues1_idx` (`league_id` ASC) VISIBLE,
  CONSTRAINT `fk_applicants_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_applicants_leagues1`
    FOREIGN KEY (`league_id`)
    REFERENCES `cocdb`.`leagues` (`league_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`books` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`books` (
  `book_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `thumbnail_url` VARCHAR(255) NOT NULL,
  `ebook_url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `is_hidden` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0: Not hidden, 1: Hidden',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_books_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`book_league_mappings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`book_league_mappings` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`book_league_mappings` (
  `book_id` INT(11) UNSIGNED NOT NULL,
  `league_id` INT(11) UNSIGNED NOT NULL,
  `total_score` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `fk_book_league_mappings_books1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_book_league_mappings_leagues1_idx` (`league_id` ASC) VISIBLE,
  PRIMARY KEY (`book_id`, `league_id`),
  CONSTRAINT `fk_book_league_mappings_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `cocdb`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_league_mappings_leagues1`
    FOREIGN KEY (`league_id`)
    REFERENCES `cocdb`.`leagues` (`league_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`evaluations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`evaluations` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`evaluations` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `book_id` INT(11) UNSIGNED NOT NULL,
  `league_id` INT(11) UNSIGNED NULL DEFAULT NULL,
  `score` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evaluations_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_evaluations_books1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_evaluations_leagues1_idx` (`league_id` ASC) VISIBLE,
  CONSTRAINT `fk_evaluations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluations_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `cocdb`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluations_leagues1`
    FOREIGN KEY (`league_id`)
    REFERENCES `cocdb`.`leagues` (`league_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`videos` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`videos` (
  `video_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `video_url` VARCHAR(255) NOT NULL,
  `thumbnail_url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`video_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`transfer_histories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`transfer_histories` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`transfer_histories` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `status` TINYINT(2) NOT NULL COMMENT '0: Applied, 1: Approved',
  `withdrawal_amount` DECIMAL(15,0) NOT NULL,
  `transfer_fee` DECIMAL(15,0) NOT NULL,
  `transfer_amount` DECIMAL(15,0) NOT NULL COMMENT '= withdrawal_amount - transfer_fee',
  `transferred_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transfer_histories_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_transfer_histories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`blocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`blocks` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`blocks` (
  `block_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_user_id` INT(11) UNSIGNED NOT NULL,
  `to_user_id` INT(11) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`block_id`),
  INDEX `fk_blocks_users1_idx` (`from_user_id` ASC) VISIBLE,
  INDEX `fk_blocks_users2_idx` (`to_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_blocks_users1`
    FOREIGN KEY (`from_user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_blocks_users2`
    FOREIGN KEY (`to_user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cocdb`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cocdb`.`reports` ;

CREATE TABLE IF NOT EXISTS `cocdb`.`reports` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `book_id` int(11) unsigned NOT NULL,
  `reason` tinyint(2) NOT NULL,
  `comment` text DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reports_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_reports_books1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_reports_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cocdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `cocdb`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cocdb`.`points_packages`
-- -----------------------------------------------------
START TRANSACTION;
USE `cocdb`;
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (1, 'prod_80P', '80point', '80P', 120, 80, 1, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (2, 'prod_330P', '330point', '330P', 490, 330, 2, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (3, 'prod_660P', '660point', '660P', 980, 660, 3, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (4, 'prod_1980P', '1980point', '1980P', 2940, 1980, 4, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (5, 'prod_3450P', '3450point', '3450P', 5020, 3450, 5, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (6, 'prod_5500P', '5500point', '5500P', 8000, 5500, 6, '2020-12-07 20:30:00', '2020-12-07 20:30:00');
INSERT INTO `cocdb`.`points_packages` (`points_package_id`, `apple_product_id`, `google_product_id`, `name`, `price`, `points`, `display_order`, `created_at`, `updated_at`) VALUES (7, 'prod_7000P', '7000point', '7000P', 10000, 7000, 7, '2020-12-07 20:30:00', '2020-12-07 20:30:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cocdb`.`gifts`
-- -----------------------------------------------------
START TRANSACTION;
USE `cocdb`;
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (1, 'いいね！', 10, 'https://dav712ricl68.cloudfront.net/main/gift/10P_いいね！.png', 1, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (2, '星(黄)', 10, 'https://dav712ricl68.cloudfront.net/main/gift/10P_星.png', 2, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (3, '（笑）', 10, 'https://dav712ricl68.cloudfront.net/main/gift/10P_笑.png', 3, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (4, 'にんじん', 20, 'https://dav712ricl68.cloudfront.net/main/gift/20P_にんじん.png', 4, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (5, 'カッコいい！', 20, 'https://dav712ricl68.cloudfront.net/main/gift/20P_カッコいい！.png', 5, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (6, 'かわいい！', 20, 'https://dav712ricl68.cloudfront.net/main/gift/20P_かわいい！.png', 6, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (7, 'がんばって！', 20, 'https://dav712ricl68.cloudfront.net/main/gift/20P_がんばって！.png', 7, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (8, 'ステキ！', 20, 'https://dav712ricl68.cloudfront.net/main/gift/20P_ステキ！.png', 8, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (9, 'ヒヒーン！', 50, 'https://dav712ricl68.cloudfront.net/main/gift/50P_ヒヒーン！.png', 9, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (10, '拍手', 50, 'https://dav712ricl68.cloudfront.net/main/gift/50P_拍手.png', 10, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (11, 'クラッカー', 50, 'https://dav712ricl68.cloudfront.net/main/gift/50P_クラッカー.png', 11, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (12, 'おめでとう！', 50, 'https://dav712ricl68.cloudfront.net/main/gift/50P_おめでとう！.png', 12, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (13, 'よつば(30-DELUXマスコットキャラクター)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_よつば (1).png', 13, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (14, 'はな(30-DELUXマスコットキャラクター)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_はな (1).png', 14, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (15, 'ハート(赤)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_ハート赤.png', 15, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (16, 'ハート(ピンク)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_ハート桃.png', 16, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (17, 'トロフィー(銅)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_銅トロフィー.png', 17, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (18, 'メダル(銅)', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_銅メダル.png', 18, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (19, 'キラキラ', 100, 'https://dav712ricl68.cloudfront.net/main/gift/100P_キラキラ.png', 19, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (20, 'バースデーケーキ', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_バースデーケーキ.png', 20, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (21, '花束', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_花束.png', 21, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (22, '剣', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_剣.png', 22, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (23, '盾', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_盾.png', 23, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (24, 'お寿司', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_お寿司.png', 24, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (25, 'トロフィー(銀)', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_銀トロフィー.png', 25, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (26, 'メダル(銀)', 150, 'https://dav712ricl68.cloudfront.net/main/gift/150P_銀メダル.png', 26, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (27, 'トロフィー(金)', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_金トロフィー.png', 27, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (28, 'メダル(金)', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_金メダル.png', 28, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (29, 'ダイヤの指輪', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_ダイヤの指輪.png', 29, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (30, 'ダイヤのネックレス', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_ダイヤのネックレス.png', 30, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (31, 'ダイヤイヤリング', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_ダイヤのイヤリング.png', 31, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (32, 'エメラルドの指輪', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_エメラルドの指輪.png', 32, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (33, 'エメラルドのネックレス', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_エメラルドのネックレス.png', 33, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (34, 'エメラルドのイヤリング', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_エメラルドのイヤリング.png', 34, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (35, 'サファイアの指輪', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_サファイアの指輪.png', 35, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (36, 'サファイアのネックレス', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_サファイアのネックレス.png', 36, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (37, 'サファイアのイヤリング', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_サファイアのイヤリング.png', 37, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (38, '金の時計', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_金の時計.png', 38, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (39, '金のネックレス', 300, 'https://dav712ricl68.cloudfront.net/main/gift/300P_金のネックレス.png', 39, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (40, 'ダイヤ', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_ダイヤ.png', 40, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (41, '車', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_車.png', 41, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (42, '鎧', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_鎧.png', 42, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (43, '兜（武田信玄）', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_兜.png', 43, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (44, '金の剣', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_金の剣.png', 44, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (45, '金の盾', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_金の盾.png', 45, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (46, '高そうな車', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_飛行機.png', 46, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (47, '飛行機', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_飛行機.png', 47, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (48, '船', 500, 'https://dav712ricl68.cloudfront.net/main/gift/500P_船.png', 48, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (49, '一軒家(赤)', 750, 'https://dav712ricl68.cloudfront.net/main/gift/750P_家赤.png', 49, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (50, '一軒家(青)', 750, 'https://dav712ricl68.cloudfront.net/main/gift/750P_家青.png', 50, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (51, '一軒家(ピンク)', 750, 'https://dav712ricl68.cloudfront.net/main/gift/750P_家桃.png', 51, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (52, '一軒家(黒)', 750, 'https://dav712ricl68.cloudfront.net/main/gift/750P_家黒.png', 52, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (53, 'タワーマンション', 1000, 'https://dav712ricl68.cloudfront.net/main/gift/1,000P_タワーマンション.png', 53, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (54, '宮殿(洋風)', 1000, 'https://dav712ricl68.cloudfront.net/main/gift/1,000P_宮殿.png', 54, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (55, 'お城(和風)', 1000, 'https://dav712ricl68.cloudfront.net/main/gift/1,000P_城.png', 55, '2020-12-07 20:40:00', '2020-12-07 20:40:00');
INSERT INTO `cocdb`.`gifts` (`gift_id`, `name`, `points_spent`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (56, '山', 1000, 'https://dav712ricl68.cloudfront.net/main/gift/1,000P_山.png', 56, '2020-12-07 20:40:00', '2020-12-07 20:40:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cocdb`.`related_links`
-- -----------------------------------------------------
START TRANSACTION;
USE `cocdb`;
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (1, 'TeamAZURA', 'http://teamazura.jp/', 'banner.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner.png', 1, '2021-03-31 19:50:00', '2021-03-31 19:50:00');
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (2, '30-DELUX', 'http://www.30-delux.net/', 'banner_1.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner_1.png', 2, '2021-03-31 19:50:00', '2021-03-31 19:50:00');
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (3, 'J\'sPRODUCE ONLINE STORE', 'https://jsproduce-online-store.moala.live/', 'banner_2.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner_2.png', 3, '2021-03-31 19:50:00', '2021-03-31 19:50:00');
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (4, 'J\'sPRODUCE GOODS SHOP', 'https://jspro-shop.easy-myshop.jp/', 'banner_3.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner_3.png', 4, '2021-03-31 19:50:00', '2021-03-31 19:50:00');
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (5, '酒洛', 'http://www.sj-plus.com/store_info.php', 'banner_4.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner_4.png', 5, '2021-03-31 19:50:00', '2021-03-31 19:50:00');
INSERT INTO `cocdb`.`related_links` (`id`, `title`, `link_url`, `file_name`, `dir_path`, `image_url`, `display_order`, `created_at`, `updated_at`) VALUES (6, 'S.J Plus', 'http://www.sj-plus.com/', 'banner_5.png', '/main/related_links', 'https://dav712ricl68.cloudfront.net/main/related_links/banner_5.png', 6, '2021-03-31 19:50:00', '2021-03-31 19:50:00');

COMMIT;

